import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { useAuthTelegram } from "@workspace/api-client-react";
import { useAuth } from "@/lib/auth";
import { useTranslation } from "react-i18next";
import { ShieldCheck, Store, ArrowRight, Loader2 } from "lucide-react";
import { toast } from "@/hooks/use-toast";
export default function AuthWelcome() {
  const [, setLocation] = useLocation(); const { login } = useAuth(); const { t } = useTranslation(); const { mutate: authenticate, isPending } = useAuthTelegram();
  const signIn = () => { const initData = (window as any).Telegram?.WebApp?.initData || (import.meta.env.DEV ? "dev_mode" : ""); if (!initData) return toast({ title: "Open TeleShop inside Telegram", description: "Telegram authentication data is not available.", variant: "destructive" }); authenticate({ data: { initData } }, { onSuccess: (data) => { login(data.token, data.user); setLocation("/"); }, onError: () => toast({ title: "Could not authenticate", variant: "destructive" }) }); };
  return <div className="flex min-h-[100dvh] flex-col justify-between px-5 py-8"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-primary-foreground"><Store className="h-4 w-4" /></span><span className="font-mono text-xs font-bold uppercase tracking-[0.1em]">TeleShop</span></div><span className="rounded-md border border-primary/20 bg-primary/[0.06] px-2 py-1 font-mono text-[9px] uppercase text-primary">Telegram Mini App</span></div><main className="py-12"><p className="eyebrow mb-4">Digital commerce infrastructure</p><h1 className="max-w-[360px] text-[38px] font-semibold leading-[1.02] tracking-[-0.055em]">Buy, sell and distribute digital products.</h1><p className="mt-5 max-w-[340px] text-sm leading-6 text-muted-foreground">{t("auth.tagline")}</p><div className="app-surface mt-8 divide-y divide-white/[0.07]"><Benefit text="Telegram-authenticated customer identity" /><Benefit text="Recorded payment and fulfillment events" /><Benefit text="Seller, reseller and affiliate workflows" /></div></main><footer className="space-y-3"><Button onClick={signIn} disabled={isPending} className="h-12 w-full rounded-lg font-mono text-xs font-bold uppercase tracking-[0.08em]">{isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <>{t("auth.signIn")} <ArrowRight className="ml-2 h-4 w-4" /></>}</Button><Button variant="outline" onClick={() => setLocation("/")} className="h-12 w-full rounded-lg border-white/[0.09] bg-transparent">{t("auth.browseGuest")}</Button><Link href="/register-shop" className="flex min-h-11 items-center justify-center text-xs font-medium text-primary">{t("auth.openShop")}</Link></footer></div>;
}
function Benefit({ text }: { text: string }) { return <div className="flex min-h-14 items-center gap-3 px-4 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-primary" />{text}</div>; }
