import { useParams, Link } from "wouter";
import { useGetShop, useListProducts } from "@workspace/api-client-react";
import { Skeleton } from "@/components/ui/skeleton";
import { ArrowLeft, Store, Package, ShieldCheck, ArrowRight } from "lucide-react";
import { formatPrice } from "@/lib/utils";
export default function ShopPage() {
  const { shopId } = useParams(); const id = Number(shopId) || 0; const { data: shop, isLoading } = useGetShop(id, { query: { enabled: id > 0 } }); const { data: products, isLoading: productsLoading } = useListProducts(id ? { shopId: id } : undefined);
  if (isLoading) return <div className="space-y-4 p-4"><Skeleton className="h-40 rounded-xl" /><Skeleton className="h-24 rounded-xl" /></div>; if (!shop) return <div className="p-8 text-center text-sm text-muted-foreground">Shop not found</div>;
  return <div className="pb-8"><div className="flex items-center gap-3 border-b border-white/[0.07] px-4 py-3"><Link href="/" className="grid h-11 w-11 place-items-center rounded-lg border border-white/[0.09] bg-card"><ArrowLeft className="h-4 w-4" /></Link><div><p className="eyebrow mb-1">Storefront</p><p className="text-sm font-medium">@{shop.slug}</p></div></div><div className="space-y-6 px-4 py-5"><section className="app-surface p-5"><div className="flex items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-lg border border-primary/20 bg-primary/[0.06] text-primary"><Store className="h-6 w-6" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h1 className="truncate text-xl font-semibold">{shop.name}</h1>{shop.status === "active" && <ShieldCheck className="h-4 w-4 text-primary" />}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{shop.description || "This seller has not added a description."}</p></div></div><div className="mt-4 flex gap-4 border-t border-white/[0.07] pt-3 font-mono text-[10px] uppercase text-muted-foreground"><span>{shop.status}</span><span>{shop.plan} plan</span></div></section><section><div className="mb-3 flex items-end justify-between"><div><p className="eyebrow mb-1.5">Catalog</p><h2 className="text-lg font-semibold">Available products</h2></div><span className="font-mono text-[10px] text-muted-foreground">{products?.total ?? 0} ITEMS</span></div>{productsLoading ? <div className="grid grid-cols-2 gap-3">{[1,2,3,4].map((item) => <Skeleton key={item} className="h-52 rounded-xl" />)}</div> : products?.items.length ? <div className="grid grid-cols-2 gap-3">{products.items.map((product) => <Link key={product.id} href={`/product/${product.id}`} className="app-surface group overflow-hidden"><div className="aspect-square bg-[#0d1015]">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><Package className="h-5 w-5 text-muted-foreground" /></div>}</div><div className="border-t border-white/[0.07] p-3"><p className="truncate text-xs font-medium">{product.name}</p><div className="mt-2 flex items-center justify-between"><p className="mono-value text-[11px] font-semibold text-primary">{formatPrice(product.price)} {product.currency}</p><ArrowRight className="h-3.5 w-3.5 text-muted-foreground" /></div></div></Link>)}</div> : <div className="app-surface p-10 text-center text-xs text-muted-foreground">No active products from this shop.</div>}</section></div></div>;
}
