import { useAuth } from "@/lib/auth";
import { Link } from "wouter";
import { User, Package, LogOut, ArrowRight, Store, Globe, Wallet, ShieldCheck } from "lucide-react";
import { useTranslation } from "react-i18next";
import { setLanguage, LANGUAGES } from "@/lib/i18n";
import { useState } from "react";
import i18n from "@/lib/i18n";
export default function UserProfile() {
  const { user, logout } = useAuth(); const { t } = useTranslation(); const [showLanguages, setShowLanguages] = useState(false); if (!user) return <div className="p-8 text-center text-sm text-muted-foreground">{t("profile.pleaseLogin")}</div>;
  return <div className="space-y-6 px-4 py-5 pb-24"><section className="app-surface overflow-hidden"><div className="flex items-center gap-4 border-b border-white/[0.07] p-4"><span className="grid h-14 w-14 place-items-center rounded-lg border border-white/[0.09] bg-white/[0.04]"><User className="h-6 w-6 text-primary" /></span><div className="min-w-0 flex-1"><p className="eyebrow mb-1.5">Telegram identity</p><h1 className="truncate text-lg font-semibold">{user.username || "Telegram User"}</h1><p className="mt-1 font-mono text-[10px] text-muted-foreground">ID {user.telegramId}</p></div><ShieldCheck className="h-4 w-4 text-primary" /></div><div className="grid grid-cols-3 divide-x divide-white/[0.07] p-1"><Shortcut href="/orders" icon={Package} label="Orders" /><Shortcut href="/dashboard" icon={Store} label="Sell" /><Shortcut href="/wallet" icon={Wallet} label="Wallet" /></div></section><section><p className="eyebrow mb-3">Account</p><div className="app-surface overflow-hidden"><Menu href="/orders" icon={Package} label={t("profile.myOrders")} /><Menu href="/dashboard" icon={Store} label={t("profile.merchantDashboard")} /><Menu href="/wallet" icon={Wallet} label={t("profile.wallet")} /></div></section><section><p className="eyebrow mb-3">Preferences</p><div className="app-surface overflow-hidden"><button onClick={() => setShowLanguages(!showLanguages)} className="flex min-h-14 w-full items-center gap-3 border-b border-white/[0.07] px-4 text-left"><Globe className="h-4 w-4 text-muted-foreground" /><span className="flex-1 text-sm font-medium">{t("profile.language")}</span><span className="text-sm">{LANGUAGES.find((item) => item.code === i18n.language)?.flag ?? "🌐"}</span></button>{showLanguages && <div className="border-b border-white/[0.07] bg-[#0d1015] p-2">{LANGUAGES.map((language) => <button key={language.code} onClick={() => { setLanguage(language.code); setShowLanguages(false); }} className={`flex min-h-11 w-full items-center gap-3 rounded-md px-3 text-xs ${i18n.language === language.code ? "bg-primary/[0.08] text-primary" : "text-muted-foreground"}`}><span>{language.flag}</span><span>{language.label}</span>{i18n.language === language.code && <span className="ml-auto">✓</span>}</button>)}</div>}<button onClick={() => { logout(); window.location.href = "/welcome"; }} className="flex min-h-14 w-full items-center gap-3 px-4 text-left text-red-300"><LogOut className="h-4 w-4" /><span className="text-sm font-medium">{t("profile.signOut")}</span></button></div></section></div>;
}
function Menu({ href, icon: Icon, label }: { href: string; icon: typeof Package; label: string }) { return <Link href={href} className="flex min-h-14 items-center gap-3 border-b border-white/[0.07] px-4 last:border-0"><Icon className="h-4 w-4 text-primary" /><span className="flex-1 text-sm font-medium">{label}</span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>; }
function Shortcut({ href, icon: Icon, label }: { href: string; icon: typeof Package; label: string }) { return <Link href={href} className="flex min-h-[72px] flex-col items-center justify-center gap-2 text-[10px] font-medium text-muted-foreground"><Icon className="h-4 w-4 text-primary" />{label}</Link>; }
