// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teleshop/Marketplace.tsx": () => import("../components/mockups/teleshop/Marketplace.tsx"),
  "./components/mockups/teleshop/MerchantDashboard.tsx": () => import("../components/mockups/teleshop/MerchantDashboard.tsx"),
  "./components/mockups/teleshop/ProductDetail.tsx": () => import("../components/mockups/teleshop/ProductDetail.tsx"),
  "./components/mockups/teleshop/ShopPage.tsx": () => import("../components/mockups/teleshop/ShopPage.tsx")
};
